### ISSUE TITLE
ETCD-48 Failure

### ISSUE THREAD

**Issue by fenar** [juju-solutions/layer-etcd#106]
2017-08-28 15:06:55 INFO juju-log Initializing Leadership Layer (is leader)
2017-08-28 15:06:55 INFO juju-log Invoking reactive handler: reactive/etcd.py:97:missing_relation_notice
2017-08-28 15:06:55 INFO juju-log Invoking reactive handler: reactive/etcd.py:405:render_default_user_ssl_exports
2017-08-28 15:06:55 INFO juju-log Invoking reactive handler: reactive/etcd.py:253:snap_install
2017-08-28 15:06:55 INFO juju-log Installing etcd from store
2017-08-28 15:07:00 INFO juju.worker.leadership tracker.go:184 etcd/0 will renew etcd leadership at 2017-08-28 15:07:30.562662844 +0000 UTC
2017-08-28 15:07:05 INFO install error: cannot communicate with server: Post http://localhost/v2/snaps/etcd: dial unix /run/snapd.socket: connect: connection refused
2017-08-28 15:07:05 INFO install 
2017-08-28 15:07:05 INFO install error: cannot communicate with server: Post http://localhost/v2/snaps/etcd: dial unix /run/snapd.socket: connect: connection refused
2017-08-28 15:07:05 INFO install 
2017-08-28 15:07:05 INFO install error: cannot communicate with server: Post http://localhost/v2/snaps/etcd: dial unix /run/snapd.socket: connect: connection refused
2017-08-28 15:07:05 INFO install 
2017-08-28 15:07:05 INFO install Traceback (most recent call last):
2017-08-28 15:07:05 INFO install   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/install", line 19, in <module>
2017-08-28 15:07:05 INFO install     main()
2017-08-28 15:07:05 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-08-28 15:07:05 INFO install     bus.dispatch()
2017-08-28 15:07:05 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 423, in dispatch
2017-08-28 15:07:05 INFO install     _invoke(other_handlers)
2017-08-28 15:07:05 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 406, in _invoke
2017-08-28 15:07:05 INFO install     handler.invoke()
2017-08-28 15:07:05 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 280, in invoke
2017-08-28 15:07:05 INFO install     self._action(*args)
2017-08-28 15:07:05 INFO install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 257, in snap_install
2017-08-28 15:07:05 INFO install     snap.install('etcd', channel=channel, classic=True)
2017-08-28 15:07:05 INFO install   File "lib/charms/layer/snap.py", line 45, in install
2017-08-28 15:07:05 INFO install     _install_store(snapname, **kw)
2017-08-28 15:07:05 INFO install   File "lib/charms/layer/snap.py", line 147, in _install_store
2017-08-28 15:07:05 INFO install     stderr=subprocess.STDOUT)
2017-08-28 15:07:05 INFO install   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2017-08-28 15:07:05 INFO install     **kwargs).stdout
2017-08-28 15:07:05 INFO install   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2017-08-28 15:07:05 INFO install     output=stdout, stderr=stderr)
2017-08-28 15:07:05 INFO install subprocess.CalledProcessError: Command '['snap', 'install', '--channel=2.3/stable', '--classic', 'etcd']' returned non-zero exit status 1
2017-08-28 15:07:05 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

**Comment by Cynerva** [comment]
Thanks for the report. This looks like the same issue as https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/393

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809382.
