### ISSUE TITLE
New setuptools_scm causing upgrade-charm failure

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/layer-etcd#130]
```
unit-etcd-1: 12:07:53 DEBUG unit.etcd/1.upgrade-charm Ignoring indexes: https://pypi.python.org/simple
unit-etcd-1: 12:07:53 DEBUG unit.etcd/1.upgrade-charm Requirement already up-to-date: pip in /var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages
unit-etcd-1: 12:07:54 DEBUG unit.etcd/1.upgrade-charm Ignoring indexes: https://pypi.python.org/simple
unit-etcd-1: 12:07:54 DEBUG unit.etcd/1.upgrade-charm Requirement already up-to-date: setuptools in /var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages
unit-etcd-1: 12:07:54 DEBUG unit.etcd/1.upgrade-charm Collecting setuptools-scm
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     Complete output from command python setup.py egg_info:
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     running egg_info
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     creating pip-egg-info/setuptools_scm.egg-info
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     writing entry points to pip-egg-info/setuptools_scm.egg-info/entry_points.txt
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     writing top-level names to pip-egg-info/setuptools_scm.egg-info/top_level.txt
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     writing pip-egg-info/setuptools_scm.egg-info/PKG-INFO
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     writing dependency_links to pip-egg-info/setuptools_scm.egg-info/dependency_links.txt
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     writing manifest file 'pip-egg-info/setuptools_scm.egg-info/SOURCES.txt'
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     /tmp/pip-build-i58fd5zy/setuptools-scm/src/setuptools_scm/version.py:191: UserWarning: meta invoked without explicit configuration, will use defaults where required.
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       "meta invoked without explicit configuration,"
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     Traceback (most recent call last):
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2332, in resolve
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         return functools.reduce(getattr, self.attrs, module)
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     AttributeError: module 'setuptools_scm.hg' has no attribute 'FILES_COMMAND'
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     During handling of the above exception, another exception occurred:
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     Traceback (most recent call last):
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "<string>", line 1, in <module>
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/tmp/pip-build-i58fd5zy/setuptools-scm/setup.py", line 116, in <module>
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         setuptools.setup(**arguments)
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         return distutils.core.setup(**attrs)
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         dist.run_commands()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         self.run_command(cmd)
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         cmd_obj.run()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 278, in run
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         self.find_sources()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         mm.run()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 524, in run
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         self.add_defaults()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 563, in add_defaults
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         rcfiles = list(walk_revctrl())
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         for item in ep.load()(dirname):
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/tmp/pip-build-i58fd5zy/setuptools-scm/src/setuptools_scm/integration.py", line 28, in find_files
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         command = ep.load()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in load
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         return self.resolve()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm       File "/var/lib/juju/agents/unit-etcd-1/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2334, in resolve
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm         raise ImportError(str(exc))
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     ImportError: module 'setuptools_scm.hg' has no attribute 'FILES_COMMAND'
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     ----------------------------------------
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i58fd5zy/setuptools-scm/
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm Traceback (most recent call last):
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm   File "/var/lib/juju/agents/unit-etcd-1/charm/hooks/upgrade-charm", line 17, in <module>
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     basic.bootstrap_charm_deps()
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm   File "lib/charms/layer/basic.py", line 90, in bootstrap_charm_deps
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     'setuptools', 'setuptools-scm'])
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm     raise CalledProcessError(retcode, cmd)
unit-etcd-1: 12:07:55 DEBUG unit.etcd/1.upgrade-charm subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-etcd-1/.venv/bin/pip', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'setuptools', 'setuptools-scm']' returned non-zero exit status 1
unit-etcd-1: 12:07:55 ERROR juju.worker.uniter.operation hook "upgrade-charm" failed: exit status 1
```

A release was made today, and setuptools_scm is not pinned in `wheelhouse.txt`.

**Comment by Cynerva** [comment]
I believe this should be fixed thanks to https://github.com/juju-solutions/layer-etcd/pull/131 and https://github.com/juju-solutions/layer-etcd/pull/132. @battlemidget can you confirm? Safe to close this?

**Comment by battlemidget** [comment]
Thanks, this was addressed
