### ISSUE TITLE
Traceback when scaling etcd down

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/layer-etcd#138]
```
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken Traceback (most recent call last):
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "lib/etcdctl.py", line 157, in run
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     return check_output(split(command)).decode('ascii')
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     **kwargs).stdout
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/usr/lib/python3.5/subprocess.py", line 708, in run
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     output=stdout, stderr=stderr)
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken subprocess.CalledProcessError: Command '['/snap/bin/etcd.etcdctl', '--endpoint', 'https://172.31.69.41:2379', 'member', 'remove', '3040be6455feb4e9']' returned non-zero exit status 1
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken 
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken The above exception was the direct cause of the following exception:
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken 
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken Traceback (most recent call last):
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/cluster-relation-broken", line 19, in <module>
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     main()
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     bus.dispatch(restricted=restricted_mode)
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 374, in dispatch
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     _invoke(hook_handlers)
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 358, in _invoke
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     handler.invoke()
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 180, in invoke
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     self._action(*args)
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 469, in perform_self_unregistration
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     etcdctl.unregister(members[unit_name]['unit_id'], leader_address)
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "lib/etcdctl.py", line 75, in unregister
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     return self.run(command)
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken   File "lib/etcdctl.py", line 160, in run
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken     raise EtcdCtl.CommandFailed() from e
unit-etcd-0: 20:11:11 DEBUG unit.etcd/0.cluster-relation-broken etcdctl.CommandFailed
unit-etcd-0: 20:11:11 ERROR juju.worker.uniter.operation hook "cluster-relation-broken" failed: exit status 1
```

Our test issues a destroy_unit and waits for etcd to recover, it never does with the above traceback being seen repeatedly.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809384.
