### ISSUE TITLE
Error:  client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-etcd#18]
I encountered an edge case where the 11th etcd unit didn't register.

```
unit-etcd-10: 2016-06-03 21:35:39 INFO unit.etcd/10.certificates-relation-changed logger.go:40 context deadline exceeded
unit-etcd-10: 2016-06-03 21:35:39 WARNING unit.etcd/10.juju-log server.go:269 certificates:0: Notice:  Unit failed self registration
unit-etcd-10: 2016-06-03 21:35:39 INFO unit.etcd/10.juju-log server.go:269 certificates:0: Writing file /etc/default/etcd root:root 444
unit-etcd-10: 2016-06-03 21:35:39 INFO unit.etcd/10.certificates-relation-changed logger.go:40 Job for etcd.service failed because the control process exited with error code. See "systemctl status etcd.service" and "journalctl -xe" 
for details.
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40 Error:  client: etcd cluster is unavailable or misconfigured
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40 error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40 error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40 
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40 Traceback (most recent call last):
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-etcd-10/charm/hooks/certificates-relation-changed", line 19, in <module>
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     main()
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 73, in main
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     bus.dispatch()
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 421, in dispatch
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     _invoke(other_handlers)
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 404, in _invoke
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     handler.invoke()
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 280, in invoke
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     self._action(*args)
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-etcd-10/charm/reactive/etcd.py", line 197, in register_node_with_leader
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     status = etcdctl.cluster_health()
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "lib/etcdctl.py", line 96, in cluster_health
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     out = self.run('etcdctl cluster-health')
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "lib/etcdctl.py", line 106, in run
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     return check_output(split(command)).decode('ascii')
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     **kwargs).stdout
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40   File "/usr/lib/python3.5/subprocess.py", line 708, in run
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40     output=stdout, stderr=stderr)
unit-etcd-10: 2016-06-03 21:35:41 INFO unit.etcd/10.certificates-relation-changed logger.go:40 subprocess.CalledProcessError: Command '['etcdctl', 'cluster-health']' returned non-zero exit status 4
unit-etcd-10: 2016-06-03 21:35:42 ERROR juju.worker.uniter.operation runhook.go:107 hook "certificates-relation-changed" failed: exit status 1
```

It looks like we can make run catch the CalledProcessError and avoid this situation.

**Comment by chuckbutler** [comment]
Closed with #19
