### ISSUE TITLE
hook error on proxy-relation-joined. 

### ISSUE THREAD

**Issue by raema** [juju-solutions/layer-etcd#33]
Using cs:~containers/etcd-4 I am seeing a hook error when relating with neutron-calico

So far etcd installs, but when it is related to neutron-calico there is a hook error. The hook is running 'etcdctl member list' which complains about server.pem not being available.

« juju status etcd
[Services] 
NAME       STATUS EXPOSED CHARM               
etcd       error  false   local:xenial/etcd-0 

[Relations] 
SERVICE1    SERVICE2           RELATION TYPE    
etcd        etcd               cluster  peer    
etcd        neutron-api        proxy    regular 
etcd        neutron-calico-c06 proxy    regular 
etcd        neutron-calico-c07 proxy    regular 

[Units] 
ID      WORKLOAD-STATUS JUJU-STATUS VERSION   MACHINE   PORTS    PUBLIC-ADDRESS MESSAGE                                                                
etcd/1  active          idle        2.0-beta7 28/lxd/9  2379/tcp 172.16.39.46   (leader) cluster is healthy                                            
etcd/2  error           idle        2.0-beta7 28/lxd/10          172.16.39.47   hook failed: "proxy-relation-joined" for neutron-api:etcd-proxy        
etcd/3  error           idle        2.0-beta7 28/lxd/11          172.16.39.48   hook failed: "proxy-relation-joined" for neutron-calico-c07:etcd-proxy 

[Machines] 
ID         STATE   DNS          INS-ID SERIES AZ      
28         started 172.16.39.16 4y3h8h xenial default 

/var/log/juju/unit-etcd-2.log:

2016-07-19 08:23:14 DEBUG worker.uniter.jujuc server.go:174 hook context id "etcd/2-proxy-relation-joined-3469482848560550054"; dir "/var/lib/juju/agents/unit-etcd-2/charm"
2016-07-19 08:23:15 INFO proxy-relation-joined open /etc/ssl/etcd/server.pem: no such file or directory
2016-07-19 08:23:15 INFO proxy-relation-joined Traceback (most recent call last):
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/var/lib/juju/agents/unit-etcd-2/charm/hooks/proxy-relation-joined", line 19, in <module>
2016-07-19 08:23:15 INFO proxy-relation-joined     main()
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-07-19 08:23:15 INFO proxy-relation-joined     bus.dispatch()
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-07-19 08:23:15 INFO proxy-relation-joined     _invoke(other_handlers)
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-07-19 08:23:15 INFO proxy-relation-joined     handler.invoke()
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-07-19 08:23:15 INFO proxy-relation-joined     self._action(*args)
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/var/lib/juju/agents/unit-etcd-2/charm/reactive/etcd.py", line 165, in send_cluster_details
2016-07-19 08:23:15 INFO proxy-relation-joined     peers = etcdctl.member_list()
2016-07-19 08:23:15 INFO proxy-relation-joined   File "lib/etcdctl.py", line 74, in member_list
2016-07-19 08:23:15 INFO proxy-relation-joined     out = self.run("etcdctl member list")
2016-07-19 08:23:15 INFO proxy-relation-joined   File "lib/etcdctl.py", line 134, in run
2016-07-19 08:23:15 INFO proxy-relation-joined     return check_output(split(command)).decode('ascii')
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2016-07-19 08:23:15 INFO proxy-relation-joined     **kwargs).stdout
2016-07-19 08:23:15 INFO proxy-relation-joined   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2016-07-19 08:23:15 INFO proxy-relation-joined     output=stdout, stderr=stderr)
2016-07-19 08:23:15 INFO proxy-relation-joined subprocess.CalledProcessError: Command '['etcdctl', 'member', 'list']' returned non-zero exit status 1
2016-07-19 08:23:15 ERROR juju.worker.uniter.operation runhook.go:107 hook "proxy-relation-joined" failed: exit status 1
2016-07-19 08:23:15 DEBUG juju.worker.uniter uniter.go:554 unlock: etcd/2: executing operation: run relation-joined (90; neutron-api/0) hook
2016-07-19 08:23:15 INFO juju.worker.uniter resolver.go:107 awaiting error resolution for "relation-joined" hook
2016-07-19 08:23:15 DEBUG juju.worker.uniter agent.go:17 [AGENT-STATUS] error: hook failed: "proxy-relation-joined"

root@juju-machine-28-lxd-10:~# etcdctl member list
open /etc/ssl/etcd/server.pem: no such file or directory

**Comment by raema** [comment]
Full agent log:

[unit-etcd-2.log.txt](https://github.com/juju-solutions/layer-etcd/files/371926/unit-etcd-2.log.txt)

**Comment by chuckbutler** [comment]
This wasn't fully closed with #34 

I've proposed #35 as an amendment to fix what was uncovered by guarding on TLS, but not cluster status.

**Comment by neiljerram** [comment]
I'm currently using cs:~lazypower/etcd-22 for this issue.  Is there a process by which I can discover when there is a new cs:~containers/etcd-N that contains the same fix?

(Especially bearing in mind that this issue is already closed...  If it wasn't, one plausible process would be for the issue _only_ to be closed when there was a new cs:~containers/etcd-N available, and for the closing comment to mention that new cs:~containers/etcd-N.)
