### ISSUE TITLE
TImeout Error during automated testing

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-etcd#38]
The tests appear to timeout during the add-unit operation, as there's an internal hard-coded timeout value being raised here

```
ERROR: test_node_scale (__main__.TestDeployment)
Scale beyond 1 node because etcd supports peering as a standalone
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bundletester-HOsALY/etcd/tests/10-deploy", line 32, in test_node_scale
    self.d.sentry.wait()
  File "/usr/local/lib/python2.7/dist-packages/amulet/sentry.py", line 541, in wait
    for i in helpers.timeout_gen(timeout):
  File "/usr/local/lib/python2.7/dist-packages/amulet/helpers.py", line 109, in timeout_gen
    raise TimeoutError()
TimeoutError
```

This has a direct relation to:

https://github.com/juju/amulet/issues/113

**Comment by chuckbutler** [comment]
Fixed by #39, will be fully resolved when amulet is published with the 113 fix
