### ISSUE TITLE
The last etcd unit will not die!

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-etcd#43]
Running bundletester on the kubernetes-core bundle I can not get results because bundletester can not tear down all the etcd units.

Here is what I saw in the logs:

```
2016-09-03 01:41:32 INFO juju-log cluster:1: Unregistering etcd/1
2016-09-03 01:41:36 INFO cluster-relation-departed Recieved an error trying to remove member 73a184160f9b693b: client: etcd cluster is unavailable or misconfiguredTraceback (most recent call last):
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/cluster-relation-departed", line 19, in <module>
2016-09-03 01:41:36 INFO cluster-relation-departed     main()
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-09-03 01:41:36 INFO cluster-relation-departed     bus.dispatch()
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-09-03 01:41:36 INFO cluster-relation-departed     _invoke(other_handlers)
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-09-03 01:41:36 INFO cluster-relation-departed     handler.invoke()
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-09-03 01:41:36 INFO cluster-relation-departed     self._action(*args)
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 393, in unregister
2016-09-03 01:41:36 INFO cluster-relation-departed     etcdctl.unregister(members[cluster_name]['unit_id'])
2016-09-03 01:41:36 INFO cluster-relation-departed   File "lib/etcdctl.py", line 62, in unregister
2016-09-03 01:41:36 INFO cluster-relation-departed     return self.run(command)
2016-09-03 01:41:36 INFO cluster-relation-departed   File "lib/etcdctl.py", line 134, in run
2016-09-03 01:41:36 INFO cluster-relation-departed     return check_output(split(command)).decode('ascii')
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2016-09-03 01:41:36 INFO cluster-relation-departed     **kwargs).stdout
2016-09-03 01:41:36 INFO cluster-relation-departed   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2016-09-03 01:41:36 INFO cluster-relation-departed     output=stdout, stderr=stderr)
2016-09-03 01:41:36 INFO cluster-relation-departed subprocess.CalledProcessError: Command '['etcdctl', 'member', 'remove', '73a184160f9b693b']' returned non-zero exit status 1
```

Looks like that last call is not returning zero. We should make that work so the unit can die.

**Comment by chuckbutler** [comment]
This was resolved some time ago. Not sure which commit but it no longer applies to MASTER as of today
