### ISSUE TITLE
The openssl configuration code is broken

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-etcd#46]
I updated the etcd charm to use resources and in the resource I put a updated version of easy-rsa/easyrsa3/openssl-1.0.cnf with the `copy_extensions = copy` in the file.

The tls code still searches for this key and incorrectly applies a "fix" generating an error when easyrsa tries to read the config file: 
Invalid extension copy option: "copycopy_extensions = copy"

```
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install Using configuration from /var/lib/juju/agents/unit-etcd-0/charm/easy-rsa/easyrsa3/openssl-1.0.cnf
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install Invalid extension copy option: "copycopy_extensions = copy"
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install 
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install Easy-RSA error:
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install 
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install signing failed (openssl output above may have more detail)
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install Traceback (most recent call last):
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/install", line 19, in <module>
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     main()
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     bus.dispatch()
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     _invoke(other_handlers)
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     handler.invoke()
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     self._action(*args)
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/tls.py", line 96, in check_ca_status
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     create_server_certificate(path_safe_name)
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/tls.py", line 287, in create_server_certificate
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     check_call(split(server))
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install     raise CalledProcessError(retcode, cmd)
unit-etcd-0: 07:49:09 INFO unit.etcd/0.install subprocess.CalledProcessError: Command '['./easyrsa', '--batch', '--req-cn=54.153.8.13', '--subject-alt-name=IP:54.153.8.13,IP:172.31.13.38,DNS:ip-172-31-13-38', 'build-server-full', 'etcd_0', 'nopass', '2>&1']' returned non-zero exit status 1
```

**Comment by chuckbutler** [comment]
Linking against #50 so it gets fixed accordingly as an upgrade / deprecation step, isntead of a patch to an existing workaround.
