### ISSUE TITLE
Hook error during upgrade from current stable to latest candidate

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/layer-etcd#89]
```
2017-04-07 18:41:47 INFO juju-log Invoking reactive handler: reactive/etcd.py:195:send_single_connection_details
2017-04-07 18:41:48 INFO upgrade-charm Traceback (most recent call last):
2017-04-07 18:41:48 INFO upgrade-charm   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/upgrade-charm", line 28, in <module>
2017-04-07 18:41:48 INFO upgrade-charm     main()
2017-04-07 18:41:48 INFO upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-04-07 18:41:48 INFO upgrade-charm     bus.dispatch()
2017-04-07 18:41:48 INFO upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2017-04-07 18:41:48 INFO upgrade-charm     _invoke(other_handlers)
2017-04-07 18:41:48 INFO upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2017-04-07 18:41:48 INFO upgrade-charm     handler.invoke()
2017-04-07 18:41:48 INFO upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2017-04-07 18:41:48 INFO upgrade-charm     self._action(*args)
2017-04-07 18:41:48 INFO upgrade-charm   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 202, in send_single_connection_details
2017-04-07 18:41:48 INFO upgrade-charm     ca = read_tls_cert('ca.crt')
2017-04-07 18:41:48 INFO upgrade-charm   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 510, in read_tls_cert
2017-04-07 18:41:48 INFO upgrade-charm     with open(cert_paths[cert], 'r') as fp:
2017-04-07 18:41:48 INFO upgrade-charm FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/etcd/common/ca.crt'
```

**Comment by Cynerva** [comment]
This resolved itself automatically after a couple of retries.

**Comment by Cynerva** [comment]
This should be fixed via https://github.com/juju-solutions/layer-tls-client/pull/7 and https://github.com/juju-solutions/layer-etcd/pull/90, thanks @wwwtyro!
